version = 0.1

[default.deploy.parameters]
stack_name = "Remote-Detective"
resolve_s3 = true
s3_prefix = "Remote-Detective"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AllowedOrigins=\"http://localhost:5173,https://remote-detective.amplifyapp.com\" BedrockModelId=\"anthropic.claude-haiku-4-5-20251001-v1:0\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
