version = 0.1

[default.deploy.parameters]
stack_name = "Remote-Detective"
resolve_s3 = true
s3_prefix = "Remote-Detective"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AllowedOrigins=\"http://localhost:5173,http://localhost:4173,http://localhost:4174,https://main.df6sc2858b5sx.amplifyapp.com\" BedrockModelId=\"us.anthropic.claude-haiku-4-5-20251001-v1:0\" BedrockFoundationModelId=\"anthropic.claude-haiku-4-5-20251001-v1:0\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
